__all__ = [
    "DB_PATH",
    "ENV_VAR_CONFIG_PATH",
    "ENV_VAR_RECORDINGS_DIR_PATH",
    "ENV_VAR_JANUS_RTP_START_PORT",
    "MAX_TOTAL_SIZE_PERCENT",
]

ENV_VAR_CONFIG_PATH = "STREAMING_CFG_PATH"
ENV_VAR_RECORDINGS_DIR_PATH = "RECORDINGS_DIR_PATH"
ENV_VAR_JANUS_RTP_START_PORT = "JANUS_PORT_STREAMING_START"
DB_PATH = "/etc/storage.db"
MAX_TOTAL_SIZE_PERCENT = 90
